---
abstract: 'set the line number for an XML::LibXML::Node'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.021, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-LibXML-Devel-SetLineNumber
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  XML::LibXML::Devel::SetLineNumber:
    file: lib/XML/LibXML/Devel/SetLineNumber.pm
    version: '0.002'
requires:
  XML::LibXML: '1.90'
  XML::LibXML::Devel: '0'
  perl: '5.008003'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/XML-LibXML-Devel-SetLineNumber/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-LibXML-Devel-SetLineNumber
  homepage: https://metacpan.org/release/XML-LibXML-Devel-SetLineNumber
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-xml-libxml-devel-setlinenumber.git
version: '0.002'
